# zeelos - monitoring
# MAINTAINER zeelos.io - https://zeelos.io

version: '3.6'

services:
  agent:
    image: portainer/agent:1.3.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  portainer:
    image: portainer/portainer:1.21.0
    volumes:
      - portainer-data:/data
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    networks:
      - agent_network
    ports:
      - "9000:9000"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  prometheus:
    image: prom/prometheus:v2.10.0
    volumes:
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/config.yml'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=${prometheus.retention_days}'
    networks:
      - monnet
    ports:
      - published: 9091
        target: 9090
        mode: host
    configs:
      - source: prometheus_config
        target: /etc/prometheus/config.yml
      - source: prometheus_task_rules
        target: /etc/prometheus/swarm_task.rules.yml
      - source: prometheus_node_rules
        target: /etc/prometheus/swarm_node.rules.yml
    deploy:
      placement:
        constraints:
          - node.hostname == ${project.name}-${project.region}-${project.zone}-swarm-worker-5
    labels:
      io.zeelos.app: ${project.name}
      io.zeelos.role: "Prometheus - From metrics to insight, Power your metrics and alerting with a leading open-source monitoring solution"

  alertmanager:
    image: prom/alertmanager:v0.17.0
    volumes:
      - alertmanager-data:/alertmanager
    networks:
      - monnet
    ports:
      - published: 9093
        target: 9093
        mode: host
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    deploy:
      placement:
        constraints:
          - node.hostname == ${project.name}-${project.region}-${project.zone}-swarm-worker-5
    configs:
      - source: alertmanager.config
        target: /etc/alertmanager/config.yml
    labels:
      io.zeelos.app: ${project.name}
      io.zeelos.role: "alertmanager - The Alertmanager handles alerts sent by client applications such as the Prometheus server"

  cadvisor:
    image: zeelos/cadvisor:v0.33.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock,readonly
      - /:/rootfs
      - /var/run:/var/run
      - /sys:/sys
      - /var/lib/docker/:/var/lib/docker
    command: -logtostderr -docker_only
    networks:
      - monnet
    ports:
      - published: 8090
        target: 8080
        mode: host
    deploy:
      mode: global
    labels:
      io.zeelos.app: ${project.name}
      io.zeelos.role: "cAdvisor - Analyzes resource usage and performance characteristics of running containers"

  node-exporter:
    image: zeelos/node_exporter:v0.18.1
    environment:
      - NODE_ID={{.Node.ID}}
    networks:
      - monnet
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$$$|/)"'
      - '--collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$$$"'
      - '--collector.textfile.directory=/etc/node_exporter/'
    deploy:
      mode: global
    labels:
      io.zeelos.app: ${project.name}
      io.zeelos.role: "node-exporter - Exporter for machine metrics"

  docker-exporter:
    image: zeelos/docker_exporter:1.7.3.1
    environment:
      - IN=172.17.0.1:9323
      - OUT=9323
    networks:
      - monnet
    deploy:
      mode: global
    labels:
      io.zeelos.app: ${project.name}
      io.zeelos.role: "docker-exporter - Provides the possibility of cat a TCP connection to a defined PORT"

configs:
  prometheus_config:
    file: configs/prometheus/conf/config.yml
  prometheus_task_rules:
    file: configs/prometheus/rules/swarm_task.rules.yml
  prometheus_node_rules:
    file: configs/prometheus/rules/swarm_node.rules.yml
  alertmanager.config:
    file: configs/alertmanager/config.yml

volumes:  
  prometheus-data:
    driver: rexray/gcepd
    driver_opts:
      size: 20

  alertmanager-data:
    driver: rexray/gcepd
    driver_opts:
      size: 10

  portainer-data:
    driver: rexray/gcepd
    driver_opts:
      size: 10

networks:
  monnet:
    external: true
    name: monnet
  agent_network:
    driver: overlay
    attachable: true
