# zeelos - mirromaker
# MAINTAINER zeelos.io - https://zeelos.io

version: '3.6'

services:
  kafka-mirrormaker:
    image: images.zeelos.io/library/kafka-mirrormaker:5.2.1
    environment:
      - MIRRORMAKER_WHITE_LIST=^iot.${edge.id}.((?!req).)*$$$$
      - MIRRORMAKER_ABORT_ON_SEND_FAILURE=true
      - MIRRORMAKER_OFFSET_COMMIT_INTERVAL=10000
      - MIRRORMAKER_NUM_STREAMS=1
      - CONSUMER_BOOTSTRAP_SERVERS=SSL://kafka-${edge.id}-edge:9082
      - CONSUMER_GROUP_ID=mirrormaker_cloud_${edge.id}
      - CONSUMER_AUTO_OFFSET_RESET=earliest
      - KAFKA_OPTS=-javaagent:/etc/kafka/prometheus/jmx_prometheus_javaagent.jar=8080:/etc/kafka/prometheus/jmx-exporter-kafka-config.yml
      - KAFKA_HEAP_OPTS=${mirrormaker.heap_opts}
      - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false
                       -Dcom.sun.management.jmxremote.ssl=false
                       -Djava.rmi.server.hostname=kafka-mirrormaker-${edge.id}
                       -Dcom.sun.management.jmxremote.local.only=false
                       -Dcom.sun.management.jmxremote.rmi.port=9574
                       -Dcom.sun.management.jmxremote.port=9574
      - PRODUCER_BOOTSTRAP_SERVERS=SSL://kafka-cloud-1:9092,SSL://kafka-cloud-2:9092,SSL://kafka-cloud-3:9092
      - PRODUCER_COMPRESSION_TYPE=${compression.type}
      - PRODUCER_SECURITY_PROTOCOL=SSL
      - PRODUCER_SSL_TRUSTSTORE_LOCATION=/etc/kafka/secrets/kafka.client-cloud.truststore.jks
      - PRODUCER_SSL_TRUSTSTORE_PASSWORD=${ssl.truststorepass}
      - PRODUCER_SSL_KEYSTORE_LOCATION=/etc/kafka/secrets/kafka.client-cloud.keystore.jks
      - PRODUCER_SSL_KEYSTORE_PASSWORD=${ssl.keystorepass}
      - PRODUCER_SSL_KEY_PASSWORD=${ssl.keypass}
      - PRODUCER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
      - CONSUMER_SECURITY_PROTOCOL=SSL
      - CONSUMER_SSL_TRUSTSTORE_LOCATION=/etc/kafka/secrets/kafka.client-edge.truststore.jks
      - CONSUMER_SSL_TRUSTSTORE_PASSWORD=${ssl.truststorepass}
      - CONSUMER_SSL_KEYSTORE_LOCATION=/etc/kafka/secrets/kafka.client-edge.keystore.jks
      - CONSUMER_SSL_KEYSTORE_PASSWORD=${ssl.keystorepass}
      - CONSUMER_SSL_KEY_PASSWORD=${ssl.keypass}
      - CONSUMER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
    configs:
      - source: kafka.jmx-exporter-javaagent-jar
        target: /etc/kafka/prometheus/jmx_prometheus_javaagent.jar
      - source: kafka.jmx-exporter-kafka-config
        target: /etc/kafka/prometheus/jmx-exporter-kafka-config.yml
    secrets:
      - source: kafka.client-cloud.keystore.jks
        target: /etc/kafka/secrets/kafka.client-cloud.keystore.jks
      - source: kafka.client-cloud.truststore.jks
        target: /etc/kafka/secrets/kafka.client-cloud.truststore.jks
      - source: kafka.client-edge.keystore.jks
        target: /etc/kafka/secrets/kafka.client-edge.keystore.jks
      - source: kafka.client-edge.truststore.jks
        target: /etc/kafka/secrets/kafka.client-edge.truststore.jks
      - source: client_security_cloud.properties
        target: /etc/kafka/secrets/client_security_cloud.properties
      - source: client_security_edge.properties
        target: /etc/kafka/secrets/client_security_edge.properties
    networks:
      - cloudnet
      - monnet
    ports:
      - published: 9574
        target: 9574
        mode: host
    deploy:
      placement:
        constraints:
          - node.hostname == ${project.name}-${project.region}-${project.zone}-swarm-worker-4
    labels:
      io.zeelos.app: ${project.name}
      io.zeelos.role: "Kafka MirrorMaker - A stand-alone tool for copying data between two Apache Kafka clusters"
      io.zeelos.edgeId: ${edge.id}

configs:
  kafka.jmx-exporter-javaagent-jar:
    file: configs/prometheus/exporters/kafka/jmx_prometheus_javaagent-0.11.0.jar
  kafka.jmx-exporter-kafka-config:
    file: configs/prometheus/exporters/kafka/jmx-exporter-kafka-config.yml

secrets:
  kafka.client-cloud.keystore.jks:
    file: security/kafka.client-cloud.keystore.jks
  kafka.client-cloud.truststore.jks:
    file: security/kafka.client-cloud.truststore.jks
  kafka.client-edge.keystore.jks:
    file: security/kafka.client-edge.keystore.jks
  kafka.client-edge.truststore.jks:
    file: security/kafka.client-edge.truststore.jks
  client_security_cloud.properties:
    file: security/client_security_cloud.properties
  client_security_edge.properties:
    file: security/client_security_edge.properties

networks:
  monnet:
    external: true
    name: monnet
  cloudnet:
    external: true
    name: cloudnet