project: 
    name: phrasal-clover-243814
    region: europe-west3
    zone: a

ssl:
  truststorepass: itsasecret
  keystorepass: itsasecret
  keypass: itsasecret

edge:
  id: FILL ME

compression:
  type: snappy

mirrormaker:
  heap_opts: -Xms128M -Xmx128M
