project: 
    name: zeelos
    region: europe-west3
    zone: a

ssl:
  truststorepass: itsasecret
  keystorepass: itsasecret
  keypass: itsasecret

edge:
  id: FILL ME

compression:
  type: snappy

mirrormaker:
  image: zeelos/kafka-mirrormaker
  version: 5.1.0
  heap_opts: -Xms128M -Xmx128M
