project: 
    name: phrasal-clover-243814

ssl:
  truststorepass: itsasecret
  keystorepass: itsasecret
  keypass: itsasecret

compression:
  type: snappy
  
edge:
  id: FILL ME

leshan:
  heap_opts: -Xmx256M -Xms256M
