project: 
    name: zeelos-io-239412

ssl:
  truststorepass: itsasecret
  keystorepass: itsasecret
  keypass: itsasecret

compression:
  type: snappy
  
edge:
  id: FILL ME

leshan:
  heap_opts: -Xmx256M -Xms256M
