project: 
    name: zeelos
    region: europe-west3
    zone: a

ssl:
  truststorepass: itsasecret
  keystorepass: itsasecret
  keypass: itsasecret

compression:
  type: snappy
  
edge:
  id: FILL ME

leshan:
  image: zeelos/leshan-server-kafka
  version: 0.5-SNAPSHOT
  heap_opts: -Xmx256M -Xms256M
