project: 
    name: zeelos
    region: europe
    zone: west3-swarm

ssl:
  truststorepass: itsasecret
  keystorepass: itsasecret
  keypass: itsasecret

compression:
  type: snappy
  
edge:
  id: FILL ME

zookeeper:
  image: confluentinc/cp-zookeeper
  version: 5.1.0
  heap_opts: -Xmx256M -Xms256M

kafka:
  image: confluentinc/cp-kafka
  version: 5.1.0
  heap_opts: -Xmx512M -Xms512M

schema:
  image: confluentinc/cp-schema-registry
  version: 5.1.0
  heap_opts: -Xmx256M -Xms256M

rest:
  image: confluentinc/cp-kafka-rest
  version: 5.1.0
  heap_opts: -Xmx256M -Xms256M

mirrormaker:
  image: zeelos/kafka-mirrormaker
  version: 5.1.0
  heap_opts: -Xmx256M -Xms256M

command:
  image: confluentinc/cp-kafka-connect-base
  version: 5.1.0

leshan:
  image: zeelos/leshan-server-kafka
  version: 0.5-SNAPSHOT
  heap_opts: -Xmx256M -Xms256M
