project: 
    name: zeelos
    region: europe-west3
    zone: a

ssl:
  truststorepass: itsasecret
  keystorepass: itsasecret
  keypass: itsasecret
  
edge:
  id: FILL ME

kstreams:
  image: zeelos/kafka-streams-leshan
  version: 0.3-SNAPSHOT
  heap_opts: -Xmx256M -Xms256M
