# zeelos - cloud
# MAINTAINER zeelos.io - https://zeelos.io

version: '3.6'

services:
  orientdb:
    image: images.zeelos.io/library/orientdb:3.0.18-tp3-with-zeelosdb
    volumes:
      - orientdb-data:/orientdb/databases
    environment:
      - ORIENTDB_ROOT_PASSWORD=${orientdb.rootpass}
      - JAVA_OPTS=-javaagent:/etc/java/prometheus/jmx_prometheus_javaagent.jar=8080:/etc/java/prometheus/jmx-exporter-generic-config.yml
                  -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false
                  -Dcom.sun.management.jmxremote.ssl=false
                  -Djava.rmi.server.hostname=orientdb
                  -Dcom.sun.management.jmxremote.local.only=false
                  -Dcom.sun.management.jmxremote.rmi.port=9450
                  -Dcom.sun.management.jmxremote.port=9450
      - ORIENTDB_SETTINGS=-Denvironment.dumpCfgAtStartup=true -Dnetwork.token.expireTimeout=10080 -Dnetwork.socketTimeout=15000
    networks:
      - cloudnet
      - monnet
    ports:
      - published: 2424
        target: 2424
        mode: host
      - published: 2480
        target: 2480
        mode: host
      - published: 9450
        target: 9450
        mode: host
    configs:
      - source: java.jmx-exporter-javaagent-jar
        target: /etc/java/prometheus/jmx_prometheus_javaagent.jar
      - source: java.jmx-exporter-generic-config
        target: /etc/java/prometheus/jmx-exporter-generic-config.yml
    deploy:
      placement:
        constraints:
          - node.hostname == ${project.name}-${project.region}-${project.zone}-swarm-worker-5
    labels:
      io.zeelos.app: ${project.name}
      io.zeelos.role: "OrientDB - Distributed Multi-Model and Graph Database"

  influxdb:
    image: images.zeelos.io/library/influxdb:1.7.6-with-zeelosdb
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_DATA_MAX_VALUES_PER_TAG=0
      - INFLUXDB_DATA_MAX_SERIES_PER_DATABASE=0
    networks:
      - cloudnet
    ports:
      - published: 8086
        target: 8086
        mode: host
    deploy:
      placement:
        constraints:
          - node.hostname == ${project.name}-${project.region}-${project.zone}-swarm-worker-5
    labels:
      io.zeelos.app: ${project.name}
      io.zeelos.role: "InfluxDB - The Platform for Time-Series Data"

  grafana:
    image: images.zeelos.io/library/grafana:6.1.4-influx-with-zeelosdb
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${grafana.rootpass}
      - GF_INSTALL_PLUGINS=natel-discrete-panel
    networks:
      - cloudnet
      - monnet
    ports:
      - published: 3000
        target: 3000
        mode: host
    user: "472"
    deploy:
      placement:
        constraints:
          - node.hostname == ${project.name}-${project.region}-${project.zone}-swarm-worker-5
    labels:
      io.zeelos.app: ${project.name}
      io.zeelos.role: "Grafana - Beautiful metric & analytic dashboards"

configs:
  java.jmx-exporter-javaagent-jar:
    file: ../configs/prometheus/exporters/kafka/jmx_prometheus_javaagent-0.11.0.jar
  java.jmx-exporter-generic-config:
    file: ../configs/prometheus/exporters/kafka/jmx-exporter-generic-config.yml

volumes:
  orientdb-data:
    driver: rexray/gcepd
    driver_opts:
      size: 20
  influxdb-data:
    driver: rexray/gcepd
    driver_opts:
      size: 20
  grafana-data:
    driver: rexray/gcepd
    driver_opts:
      size: 10

networks:
  monnet:
    external: true
    name: monnet
  cloudnet:
    external: true
    name: cloudnet
