project: 
    name: zeelos
    region: europe
    zone: west3-swarm

ssl:
  truststorepass: itsasecret
  keystorepass: itsasecret
  keypass: itsasecret

zookeeper:
  image: confluentinc/cp-zookeeper
  version: 5.1.0
  heap_opts: -Xmx512M -Xms512M

kafka:
  image: confluentinc/cp-kafka
  version: 5.1.0
  heap_opts: -Xmx1G -Xms1G

schema:
  image: confluentinc/cp-schema-registry
  version: 5.1.0
  heap_opts: -Xmx512M

rest:
  image: confluentinc/cp-kafka-rest
  version: 5.1.0
  heap_opts: -Xmx256M

command:
  image: confluentinc/cp-kafka-connect-base
  version: 5.1.0