# zeelos - mirromaker
# MAINTAINER zeelos.io - https://zeelos.io

version: '3.6'

services:

  kafka-mirrormaker:
    image: ${mirrormaker.image}:${mirrormaker.version}
    environment:
      - MIRRORMAKER_WHITE_LIST=^iot.${gateway.id}.((?!req).)*$$
      - MIRRORMAKER_ABORT_ON_SEND_FAILURE=true
      - MIRRORMAKER_OFFSET_COMMIT_INTERVAL=10000
      - MIRRORMAKER_NUM_STREAMS=1
      - CONSUMER_BOOTSTRAP_SERVERS=SSL://kafka-gateway:9082
      - CONSUMER_GROUP_ID=mirrormaker_cloud_${gateway.id}
      - CONSUMER_AUTO_OFFSET_RESET=earliest
      - KAFKA_HEAP_OPTS=${mirrormaker.heap_opts}
      - KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false
                       -Dcom.sun.management.jmxremote.ssl=false
                       -Djava.rmi.server.hostname=kafka-mirrormaker
                       -Dcom.sun.management.jmxremote.local.only=false
                       -Dcom.sun.management.jmxremote.rmi.port=9574
                       -Dcom.sun.management.jmxremote.port=9574
      - PRODUCER_BOOTSTRAP_SERVERS=SSL://kafka-cloud-1:9092,SSL://kafka-cloud-2:9092,SSL://kafka-cloud-3:9092
      - PRODUCER_COMPRESSION_TYPE=snappy
      - PRODUCER_SECURITY_PROTOCOL=SSL
      - PRODUCER_SSL_TRUSTSTORE_LOCATION=/etc/kafka/secrets/kafka.client-cloud.truststore.jks
      - PRODUCER_SSL_TRUSTSTORE_PASSWORD=${ssl.truststorepass}
      - PRODUCER_SSL_KEYSTORE_LOCATION=/etc/kafka/secrets/kafka.client-cloud.keystore.jks
      - PRODUCER_SSL_KEYSTORE_PASSWORD=${ssl.keystorepass}
      - PRODUCER_SSL_KEY_PASSWORD=${ssl.keypass}
      - PRODUCER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
      - CONSUMER_SECURITY_PROTOCOL=SSL
      - CONSUMER_SSL_TRUSTSTORE_LOCATION=/etc/kafka/secrets/kafka.client-gateway.truststore.jks
      - CONSUMER_SSL_TRUSTSTORE_PASSWORD=${ssl.truststorepass}
      - CONSUMER_SSL_KEYSTORE_LOCATION=/etc/kafka/secrets/kafka.client-gateway.keystore.jks
      - CONSUMER_SSL_KEYSTORE_PASSWORD=${ssl.keystorepass}
      - CONSUMER_SSL_KEY_PASSWORD=${ssl.keypass}
    secrets:
      - source: kafka.client-cloud.keystore.jks
        target: /etc/kafka/secrets/kafka.client-cloud.keystore.jks
      - source: kafka.client-cloud.truststore.jks
        target: /etc/kafka/secrets/kafka.client-cloud.truststore.jks
      - source: kafka.client-gateway.keystore.jks
        target: /etc/kafka/secrets/kafka.client-gateway.keystore.jks
      - source: kafka.client-gateway.truststore.jks
        target: /etc/kafka/secrets/kafka.client-gateway.truststore.jks
      - source: client_security_cloud.properties
        target: /etc/kafka/secrets/client_security_cloud.properties
      - source: client_security_gateway.properties
        target: /etc/kafka/secrets/client_security_gateway.properties
    networks:
      - cloudnet
    ports:
      - published: 9574
        target: 9574
        mode: host
    deploy:
      placement:
        constraints:
          - node.hostname == ${project.name}-${project.region}-${project.zone}-worker-4
    labels:
      io.zeelos.app: "zeelos"
      io.zeelos.role: "Kafka MirrorMaker - A stand-alone tool for copying data between two Apache Kafka clusters"
      io.zeelos.gatewayId: ${gateway.id}

secrets:
  kafka.client-cloud.keystore.jks:
    file: ./security/kafka.client-cloud.keystore.jks
  kafka.client-cloud.truststore.jks:
    file: ./security/kafka.client-cloud.truststore.jks
  kafka.client-gateway.keystore.jks:
    file: ./security/kafka.client-gateway.keystore.jks
  kafka.client-gateway.truststore.jks:
    file: ./security/kafka.client-gateway.truststore.jks
  client_security_cloud.properties:
    file: ./security/client_security_cloud.properties
  client_security_gateway.properties:
    file: ./security/client_security_gateway.properties

networks:
  cloudnet:
    external: true
    name: cloudnet