project: 
    name: zeelos-io-239412

ssl:
  truststorepass: itsasecret
  keystorepass: itsasecret
  keypass: itsasecret

edge:
  id: FILL ME

compression:
  type: snappy

mirrormaker:
  heap_opts: -Xms128M -Xmx128M
