zookeeper:
  image: zeelos/cp-zookeeper
  version: 5.0.0-arm64v8
  heap_opts: -Xmx64M -Xms64M

kafka:
  image: zeelos/cp-kafka
  version: 5.0.0-arm64v8
  heap_opts: -Xmx512M -Xms512M

schema:
  image: zeelos/cp-schema-registry
  version: 5.0.0-arm64v8
  heap_opts: -Xmx64M -Xms64M

rest:
  image: zeelos/cp-kafka-rest
  version: 5.0.0-arm64v8
  heap_opts: -Xmx64M -Xms64M

mirrormaker:
  image: zeelos/kafka-mirrormaker
  version: 5.0.0-arm64v8
  heap_opts: -Xmx64M -Xms64M

command:
  image: zeelos/cp-kafka-connect-base
  version: 5.0.0-arm64v8

leshan:
  image: zeelos/leshan-server-kafka
  version: 0.2-SNAPSHOT-arm64v8
  heap_opts: -Xmx256M -Xms256M

# snappy encoding on arm64 throws an exception,
# disable for now, investigate more
# see https://github.com/xerial/snappy-java/issues/209
compression:
  type: none
