zookeeper:
  image: zeelos/cp-zookeeper
  version: 5.0.0-openj9
  heap_opts: -Xmx256M -Xms256M

kafka:
  image: zeelos/cp-kafka
  version: 5.0.0-openj9
  heap_opts: -Xmx512M -Xms512M

schema:
  image: zeelos/cp-schema-registry
  version: 5.0.0-openj9
  heap_opts: -Xmx256M -Xms256M

rest:
  image: zeelos/cp-kafka-rest
  version: 5.0.0-openj9
  heap_opts: -Xmx256M -Xms256M

mirrormaker:
  image: zeelos/kafka-mirrormaker
  version: 5.0.0-openj9
  heap_opts: -Xmx256M -Xms256M

command:
  image: zeelos/cp-kafka-connect-base
  version: 5.0.0-openj9

leshan:
  image: zeelos/leshan-server-kafka
  version: 0.2-SNAPSHOT-openj9
  heap_opts: -Xmx256M -Xms256M
