zookeeper:
  image: confluentinc/cp-zookeeper
  version: 5.0.0
  heap_opts: -Xmx64M -Xms64M

kafka:
  image: confluentinc/cp-kafka
  version: 5.0.0
  heap_opts: -Xmx512M -Xms512M

schema:
  image: confluentinc/cp-schema-registry
  version: 5.0.0
  heap_opts: -Xmx64M -Xms64M

rest:
  image: confluentinc/cp-kafka-rest
  version: 5.0.0
  heap_opts: -Xmx64M -Xms64M

mirrormaker:
  image: zeelos/kafka-mirrormaker
  version: 5.0.0
  heap_opts: -Xmx64M -Xms64M

command:
  image: confluentinc/cp-kafka-connect-base
  version: 5.0.0

leshan:
  image: zeelos/leshan-server-kafka
  version: 0.2-SNAPSHOT
  heap_opts: -Xmx256M -Xms256M
